# Generated by Django 6.0.3 on 2026-03-19 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('direct', 'Direct'), ('booking_com', 'Booking.com'), ('airbnb', 'Airbnb'), ('phone', 'Phone'), ('walkin', 'Walk-in')], default='direct', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='confirmed', max_length=20)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('num_guests', models.PositiveIntegerField(default=1)),
                ('num_nights', models.PositiveIntegerField(default=0, editable=False)),
                ('total_price_gel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount_gel', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bog_ipay', 'BOG iPay'), ('tbc_pay', 'TBC Pay'), ('bank_transfer', 'Bank Transfer'), ('channel', 'Channel')], max_length=20, null=True)),
                ('guest_name', models.CharField(max_length=200)),
                ('guest_phone', models.CharField(blank=True, max_length=20)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('guest_country', models.CharField(blank=True, max_length=2)),
                ('notes', models.TextField(blank=True)),
                ('guest_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='guests.guest')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='properties.property')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='properties.room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomNight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_nights', to='bookings.booking')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_nights', to='properties.room')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('room', 'date'), name='unique_room_night')],
                'unique_together': {('room', 'date')},
            },
        ),
    ]
