# Generated by Django 6.0.3 on 2026-03-19 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ka', models.CharField(max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('property_type', models.CharField(choices=[('guesthouse', 'Guesthouse'), ('hotel', 'Hotel'), ('apartment', 'Apartment'), ('villa', 'Villa')], default='guesthouse', max_length=20)),
                ('description_ka', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('address_ka', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(choices=[('tbilisi', 'Tbilisi'), ('kakheti', 'Kakheti'), ('imereti', 'Imereti'), ('adjara', 'Adjara'), ('svaneti', 'Svaneti'), ('mtskheta_mtianeti', 'Mtskheta-Mtianeti'), ('guria', 'Guria'), ('samegrelo', 'Samegrelo'), ('racha', 'Racha'), ('kvemo_kartli', 'Kvemo Kartli'), ('shida_kartli', 'Shida Kartli'), ('samtskhe_javakheti', 'Samtskhe-Javakheti')], default='tbilisi', max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('check_in_time', models.TimeField(default='14:00')),
                ('check_out_time', models.TimeField(default='12:00')),
                ('house_rules_ka', models.TextField(blank=True)),
                ('house_rules_en', models.TextField(blank=True)),
                ('tax_id', models.CharField(blank=True, max_length=20)),
                ('amenities', models.JSONField(default=list)),
                ('photos', models.JSONField(default=list)),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('business', 'Business')], default='starter', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'properties',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ka', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('twin', 'Twin'), ('family', 'Family'), ('suite', 'Suite'), ('dorm', 'Dorm')], default='double', max_length=20)),
                ('max_guests', models.PositiveIntegerField(default=2)),
                ('base_price_gel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description_ka', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('amenities', models.JSONField(default=list)),
                ('photos', models.JSONField(default=list)),
                ('floor', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='properties.property')),
            ],
            options={
                'ordering': ['sort_order', 'name_ka'],
            },
        ),
        migrations.CreateModel(
            name='SeasonalRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ka', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price_gel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_stay', models.PositiveIntegerField(default=1)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_rates', to='properties.room')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
