# Generated by Django 6.0.2 on 2026-03-20 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('whatsapp', 'WhatsApp'), ('viber', 'Viber'), ('telegram', 'Telegram'), ('sms', 'SMS'), ('email', 'Email'), ('copy_link', 'Copy Link'), ('qr_download', 'QR Download'), ('qr_print', 'QR Print'), ('native_share', 'Native Share')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_events', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
