# Generated by Django 6.0.3 on 2026-03-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_slug_allow_unicode'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='banner_photo',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
