# Generated by Django 6.0.2 on 2026-03-26 05:58

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_banner_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('booking_com', 'Booking.com'), ('airbnb', 'Airbnb'), ('expedia', 'Expedia')], max_length=20)),
                ('property_external_id', models.CharField(blank=True, help_text='Property ID on the external channel platform', max_length=200)),
                ('api_key', encrypted_model_fields.fields.EncryptedTextField(blank=True, default='')),
                ('api_secret', encrypted_model_fields.fields.EncryptedTextField(blank=True, default='')),
                ('sync_status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('error', 'Error'), ('pending', 'Pending Setup')], default='pending', max_length=20)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_connections', to='properties.property')),
            ],
            options={
                'ordering': ['channel'],
                'unique_together': {('property', 'channel')},
            },
        ),
    ]
