# Generated by Django 6.0.2 on 2026-03-26 05:58

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='id_number',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default=''),
        ),
    ]
